### ISSUE TITLE
ButtonComponent prop Capitalised

### ISSUE THREAD

**Issue by Firfi** [StreakYC/react-menu-list#5]
Hello! I found that you use `ButtonComponent` prop instead of `buttonComponent` that I and many others would expect. Is it on purpose?

**Comment by AgentME** [comment]
It's intentional because I made the prop name [match the variable name used internally in react-menu-list (convenient to do with the spread operator)](https://github.com/StreakYC/react-menu-list/blob/d0048d0603074d4fd40bd20c674cac7c56478047/src/MenuButton.js#L113), and the variable name is capitalized because JSX requires component names to be capitalized. It's a convention I've used in a few components that take other components as props. I think I might have seen this done in another project beforehand.
