### ISSUE TITLE
toggle does not work

### ISSUE THREAD

**Issue by buralex** [StreakYC/react-menu-list#9]
Toggle does not work, react 16.6.1
`
class Header extends React.PureComponent {
    render() {

        return (
            <div>
                <button onClick={() => {this.menuButton.toggle();}} >
                    toggle menu
                </button>

                <MenuButton
                    ref={(elem) => { this.menuButton = elem; }}
                    menu={
                        <Dropdown>
                            <MenuList>
                                <LI>Mercury</LI>
                                <LI>Neptune</LI>
                                <LI>Neptune</LI>
                                <LI>Neptune</LI>
                                <LI>Neptune</LI>
                            </MenuList>
                        </Dropdown>
                    }
                >
                    Menu Button
                </MenuButton>
            </div>
        );
    }
}`

**Comment by Macil** [comment]
The issue is that when you click anywhere outside of MenuButton's menu, the menu closes automatically. Then .toggle() runs, always sees that the menu is closed, and opens it.

We could add an "onAutoClose" callback prop to MenuButton that gets called whenever an event happens (like a click event on an outside element) that would cause the MenuButton to auto-close, and you could cancel the auto-close behavior for a specific event.

**Comment by buralex** [comment]
Thank you for your response )
